print ("(#######)")
print ("(######*")
print ("(#####**)")
print ("(####***)")
print ("(###****)")
print ("(##*****)")
print ("(#******")
print ("(*******")
print ("~||||||||||||||||||||||~")
print ("          ‌ E                ")
print ("                H                     ")
print ("    ‌ ‌   ‌ ‌ ‌ ‌   ‌ ‌‌        S                ")
print ("                               A          ")
print ("                                       N    ")
print ("         eksperit         ")
print ("(https://1.2.3.xxxxxxxx.2.3.4.1.2xsxs.4.5.3.5.2.4.")(akante)
print ("                           ")
print ("           .             .      ")
print ("    .              .             .           ")
print ("         .                .         .                   ")
print ("~|~|~|~|~|~|~|~|~|~|~|~|~|")
print ("-+×-+×-+×-+×-+×-+×-+×-+")
print ("                                  ")
print ("   .   .   .   .   .   .   .   .   .   .   .   ")
print ("(%%%%%%%%%%%)")
print ("(%%%%%%%%%%)")
print ("(%%%%%%%%%)")
print ("(%%%%%%%%)")
print ("(%%%%%%%)")
print ("(%%%%%%)")
print ("(%%%%%)")
print ("(%%%%)")
print ("(%%%)")
print ("(%%)")
print ("(%)")
print (".           Kanale                      .")
print ("1.2.4.6.8.32..6.426371.xxx.x.xs.5.6.7.9.2.1.5.7.8.4.7.9.3.c.")
print ("*************/********")
print ("                gape           ")
print ("https://xxxxsxxxxs.com")
print ("                 bay         ")
